テキストの内容で復習

In [ ]:
!pip install gensim

In [1]:
import gensim.downloader as api

corpus = api.load("text8")


[==================================================] 100.0% 31.6/31.6MB downloaded


In [2]:
api.info('text8')

{'num_records': 1701,
 'record_format': 'list of str (tokens)',
 'file_size': 33182058,
 'reader_code': 'https://github.com/RaRe-Technologies/gensim-data/releases/download/text8/__init__.py',
 'license': 'not found',
 'description': 'First 100,000,000 bytes of plain text from Wikipedia. Used for testing purposes; see wiki-english-* for proper full Wikipedia datasets.',
 'checksum': '68799af40b6bda07dfa47a32612e5364',
 'file_name': 'text8.gz',
 'read_more': ['http://mattmahoney.net/dc/textdata.html'],
 'parts': 1}

In [3]:
from gensim.models import Word2Vec
model=Word2Vec(corpus)

In [4]:
print(model)

Word2Vec<vocab=71290, vector_size=100, alpha=0.025>


In [5]:
similarity_words=model.wv.most_similar('japan')

In [6]:
similarity_words

[('china', 0.7827277779579163),
 ('taiwan', 0.6725131273269653),
 ('indonesia', 0.6247941255569458),
 ('india', 0.616226851940155),
 ('turkey', 0.5950326919555664),
 ('singapore', 0.5851190090179443),
 ('japanese', 0.5850614309310913),
 ('pakistan', 0.5842422246932983),
 ('europe', 0.5789769887924194),
 ('thailand', 0.5761356949806213)]

Embedingの挙動の確認

In [7]:

from tensorflow.keras import Sequential
from tensorflow.keras.layers import Dense, Embedding
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras import utils


In [8]:
#text_base='Hope to see you soon. Nice to see you again.'
text_base=['Hope to see you soon.',' Nice to see you again.']

In [56]:
text1=['Hope to see you soon.']
text2=['Nice to see you again.']

In [9]:
tokenizer=Tokenizer(num_words=10)
tokenizer.fit_on_texts(text_base)


In [12]:
text1_tokenizer=tokenizer.texts_to_sequences(text1)
print(text1_tokenizer)
text1_tokenizer=pad_sequences(text1_tokenizer, maxlen=10)
text2_tokenizer=tokenizer.texts_to_sequences(text2)
print(text2_tokenizer)
text2_tokenizer=pad_sequences(text2_tokenizer, maxlen=10)

[[4, 1, 2, 3, 5]]
[[6, 1, 2, 3, 7]]


In [13]:
text_base_tokenizer=tokenizer.texts_to_sequences(text_base)
text_base_tokenizer=pad_sequences(text_base_tokenizer, maxlen=5)

In [14]:
text_base_tokenizer

array([[4, 1, 2, 3, 5],
       [6, 1, 2, 3, 7]], dtype=int32)

In [15]:
utils.set_random_seed(10)
model2=Sequential()
model2.add(Embedding(20,2))
model2.compile(optimizer='rmsprop', loss='mse')

output_array = model2.predict(text_base_tokenizer)
print(output_array)

1/1 [==============================] - 0s 98ms/step
[[[-0.0198861   0.00308717]
  [ 0.04169953  0.00088676]
  [ 0.00484879  0.02940765]
  [-0.00805895 -0.02865348]
  [ 0.02818674  0.04289735]]

 [[-0.00579723 -0.02581127]
  [ 0.04169953  0.00088676]
  [ 0.00484879  0.02940765]
  [-0.00805895 -0.02865348]
  [ 0.04063629  0.04968664]]]


In [16]:
output_array[0]

array([[-0.0198861 ,  0.00308717],
       [ 0.04169953,  0.00088676],
       [ 0.00484879,  0.02940765],
       [-0.00805895, -0.02865348],
       [ 0.02818674,  0.04289735]], dtype=float32)

In [18]:
import pandas as pd
import numpy as np

In [48]:
x=output_array[0]
y=output_array[1]

In [50]:
len(output_array[0])

5

In [44]:
x=np.array([[1,1],[1,1],[1,1]])
y=np.array([[2,2],[2,2],[2,2]])

In [61]:
lists=[]
for i in range(len(output_array[0])):
  for f in range(len(output_array[1])):
    x=output_array[0][i]
    y=output_array[1][f]
    cos_sim=np.dot(x,y)/(np.linalg.norm(x)*np.linalg.norm(y))
    if i==0:
      sent1='Hope'
    elif i==1:
      sent1='to'
    elif i==2:
      sent1='see'
    elif i==3:
      sent1='you'
    else:
      sent1='soon.'
    if f==0:
      sent2='Nice'
    elif f==1:
      sent2='to'
    elif f==2:
      sent2='see'
    elif f==3:
      sent2='you'
    else:
      sent2='again.'

    print(f'{sent1},{sent2}', cos_sim)




Hope,Nice 0.119870394
Hope,to -0.4144323
Hope,see 0.99999994
Hope,you -0.9846785
Hope,again. -0.009398132
to,Nice -0.29115602
to,to 0.56678194
to,see -0.9846785
to,you 0.99999994
to,again. 0.18362603
see,Nice -0.9938723
see,to 0.9139349
see,see -0.009398132
see,you 0.18362603
see,again. 1.0
you,Nice 1.0
you,to -0.9531963
you,see 0.119870394
you,you -0.29115602
you,again. -0.9938723
soon.,Nice -0.9531963
soon.,to 1.0
soon.,see -0.4144323
soon.,you 0.56678194
soon.,again. 0.9139349


text1=['Hope to see you soon.']
text2=['Nice to see you again.']


In [58]:
text_base=['Hope to see you soon.',' You soon hope to see.']

text_base_tokenizer=tokenizer.texts_to_sequences(text_base)
text_base_tokenizer=pad_sequences(text_base_tokenizer, maxlen=5)

utils.set_random_seed(10)
model2=Sequential()
model2.add(Embedding(20,2))
model2.compile(optimizer='rmsprop', loss='mse')

output_array = model2.predict(text_base_tokenizer)
print(output_array)

1/1 [==============================] - 0s 468ms/step
[[[-0.0198861   0.00308717]
  [ 0.04169953  0.00088676]
  [ 0.00484879  0.02940765]
  [-0.00805895 -0.02865348]
  [ 0.02818674  0.04289735]]

 [[-0.00805895 -0.02865348]
  [ 0.02818674  0.04289735]
  [-0.0198861   0.00308717]
  [ 0.04169953  0.00088676]
  [ 0.00484879  0.02940765]]]


In [59]:
for i in range(len(output_array[0])):
  for f in range(len(output_array[1])):
    x=output_array[0][i]
    y=output_array[1][f]
    cos_sim=np.dot(x,y)/(np.linalg.norm(x)*np.linalg.norm(y))
    if i==0:
      sent1='Hope'
    elif i==1:
      sent1='to'
    elif i==2:
      sent1='see'
    elif i==3:
      sent1='you'
    else:
      sent1='soon.'
    if f==0:
      sent2='You'
    elif f==1:
      sent2='soon'
    elif f==2:
      sent2='hope'
    elif f==3:
      sent2='to'
    else:
      sent2='see.'
    print(f'{sent1},{sent2}', cos_sim)


Hope,You 0.119870394
Hope,soon -0.4144323
Hope,hope 0.99999994
Hope,to -0.9846785
Hope,see. -0.009398132
to,You -0.29115602
to,soon 0.56678194
to,hope -0.9846785
to,to 0.99999994
to,see. 0.18362603
see,You -0.9938723
see,soon 0.9139349
see,hope -0.009398132
see,to 0.18362603
see,see. 1.0
you,You 1.0
you,soon -0.9531963
you,hope 0.119870394
you,to -0.29115602
you,see. -0.9938723
soon.,You -0.9531963
soon.,soon 1.0
soon.,hope -0.4144323
soon.,to 0.56678194
soon.,see. 0.9139349
